### GET a password by name
GET http://localhost:3333/api/password/wifi

### POST a new password
POST http://localhost:3333/api/passwords
Content-Type: application/json
{
    "name": "wifi",
    "value": "test-password-123"
}
